name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.2+2

environment:
  sdk: ">=3.4.3 <4.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter
  
  # Cupertino style icons
  cupertino_icons: ^1.0.8

  # for state mangement
  get: ^4.7.2

  # for api calling
  http: ^1.3.0

  # for converting csv data to list
  csv: ^6.0.0

  # local storage
  shared_preferences: 2.0.15

  # for integrating ads 
  google_mobile_ads: 2.0.0
  firebase_core: ^3.12.1
  firebase_remote_config: ^5.4.2




dev_dependencies:
  flutter_test:
    sdk: flutter

  # Encourages good practices
  flutter_lints: ^4.0.0

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/